In [26]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import zscore
import warnings
warnings.filterwarnings("ignore")

In [27]:
ruta = "../DATA/fin_mark_full_mod.csv"
df = pd.read_csv(ruta, sep=';')
import os
os.getcwd()

'c:\\Users\\hugob\\OneDrive\\Escritorio\\proyecto predicción\\trabajo_Eda\\SRC'

In [28]:
df.info()
df.shape

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         40198 non-null  object
 6   loan            40198 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41093 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41128 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  is_suscribed    41188 non-null  int64
dtypes: float64(5), int64(6), object(10)
memory usage: 6.6+ MB

(41188, 21)

In [29]:
df.head(7)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,is_suscribed
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,...,1,-1,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,0

In [30]:
df['housing'] = df['housing'].fillna('None')
df['loan'] = df['loan'].fillna('None')
df['emp.var.rate'] = df['emp.var.rate'].fillna('None')
df['euribor3m'] = df['euribor3m'].fillna('None')

In [31]:
df.isnull().sum()

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
is_suscribed      0
dtype: int64

In [32]:
df = df.drop(df[df['marital'] == 'unknown'].index)

In [33]:
df['marital'].value_counts()

marital
married     24928
single      11568
divorced     4612
Name: count, dtype: int64

In [34]:
df = df.drop(df[df['default'] == 'unknown'].index)

In [35]:
df['default'].value_counts()

default
no     32519
yes        3
Name: count, dtype: int64

In [36]:
df = df.drop(df[df['housing'] == 'unknown'].index)

In [37]:
df['housing'].value_counts()

housing
yes     17180
no      14580
None      762
Name: count, dtype: int64

In [38]:
df = df.drop(df[df['loan'] == 'unknown'].index)

In [39]:
df['loan'].value_counts()

loan
no      26794
yes      4966
None      762
Name: count, dtype: int64

In [40]:
df = df.drop(df[df['emp.var.rate'] == 'unknown'].index)

In [41]:
df['emp.var.rate'].value_counts()

emp.var.rate
 1.4     11877
-1.8      7828
 1.1      5287
-0.1      3252
-2.9      1609
-3.4      1046
-1.7       758
-1.1       620
-3.0       165
 None       70
-0.2        10
Name: count, dtype: int64

las filas desde marital hasta esta ultima estoy eliminando los valores desconocidos con el df.drop

In [42]:
df['pdays'] = df['pdays'].replace(-1, 'no_previous_contact').astype('object') 
df['is_suscribed'] = df['is_suscribed'].astype('object')

cambio el -1 de pdays por no contacto previo para entenderlo mejor cuando lo grafique y ademas lo cambio a objeto. con is suscribed hago lo mismo, lo paso a objeto ya que estaba como numerica

In [ ]:
df['is_suscribed'].value_counts()

cuento los valores unicos de is suscribed para saber cuantos estan suscritos y cuantos no (0 = no 1 = si)

In [ ]:
sns.countplot(data=df, x='is_suscribed')
plt.show()

esta celda es solo para visualizar que clientes han suscrito el deposito a plazo y cuales no lo han hecho

In [44]:
df.describe()

,age,duration,campaign,previous,cons.price.idx,cons.conf.idx,nr.employed
count,32522.000000,32522.000000,32522.000000,32522.000000,32522.000000,32522.000000,32522.000000
mean,39.140305,259.705584,2.519648,0.198789,93.525970,-40.564255,5160.019224
std,10.476884,260.985418,2.705813,0.532451,0.588434,4.803599,75.802911
min,17.000000,0.000000,1.000000,0.000000,92.201000,-50.800000,4963.600000
25%,31.000000,103.000000,1.000000,0.000000,93.075000,-42.700000,5099.100000
50%,37.000000,181.000000,2.000000,0.000000,93.444000,-41.800000,5191.000000
75%,46.000000,321.000000,3.000000,0.000000,93.994000,-36.400000,5228.100000
max,95.000000,4918.000000,43.000000,7.000000,94.767000,-26.900000,5228.100000

In [ ]:
categorical_vars = df.select_dtypes(include=['object']).columns.tolist()
numerical_vars = df.select_dtypes(include=['number']).columns.tolist()

print("Variables categóricas:", categorical_vars)
print("Variables numéricas:", numerical_vars)

separar categoricas y numericas

In [ ]:
for col in categorical_vars: 
    plt.figure(figsize=(8, 4)) 
    sns.countplot(data=df, x=col, order=df[col].value_counts().index) 
    plt.title(f"Distribución (categórica) de {col}") 
    plt.xticks(rotation=45) 
    plt.show() 

for col in numerical_vars: 
    plt.figure(figsize=(8, 4)) 
    sns.histplot(data=df, x=col, kde=True, color="blue", bins=30) 
    plt.title(f"Distribución (numérica) de {col}") 
    plt.show()

el bucle for recorre toda las variables categoricas y numericas, el seabron se utiliza para hacer el gráfico(en este caso lo he hecho de barras) el .figure es para establecer un tamaño para cada grafico y el xticks es para rotar los valores para que se vean bien  

en la parte de las numericas en vez de hacer un countplot utilizo un histograma en el que Kde color y bins son cosas para mejorar la visualizacion y estetica del histograma (PE: kde es para meter una linea de densidad o bins para que en este caso haya 30 barras )

por lo que he visto, la variable default la podemos omitir ya que no aporta valor

In [ ]:
numeric_cols_low_cardinality = [col for col in numerical_vars if df[col].nunique() < 50]
df[numeric_cols_low_cardinality].describe(percentiles=[.25, .5, .75, .9, .95, .99]).T.sort_values(by='50%', ascending=False)

una vez que he observado las variables en el analisis univariado, veo aquellas variables numericas con baja cardinalidad.
No lo he hecho con ia pero si me he apoyado de tu codigo para hacerlo

In [ ]:
df_low_c_logged = df[numeric_cols_low_cardinality].copy()
for col in df_low_c_logged.columns:
    if df_low_c_logged[col].min() > 0:
        df_low_c_logged[col] = np.log(df_low_c_logged[col])
    else:
        df_low_c_logged[col] = np.log(df_low_c_logged[col] + 1)

en esta celda, aplicamos un logaritmo para las variables que tengan baja cardinalidad. En este caso no hay datos extremadamente sesgados, pero si que viene bien hacerlo para que los datos estén lo mas juntos posibles. Esta celda tambien esta inspirada de tu codigo.

In [ ]:
for col in categorical_vars: 
    plt.figure(figsize=(10, 5)) 
    sns.countplot(data=df, x=col, hue='is_suscribed', order=df[col].value_counts().index) 
    plt.title(f"Distribución de {col} por suscripción") 
    plt.xticks(rotation=50) 
    plt.show()

for col in numerical_vars: 
    plt.figure(figsize=(10, 5)) 
    sns.boxplot(data=df, x='is_suscribed', y=col) 
    plt.title(f"Distribución de {col} por suscripción") 
    plt.show()

en este caso, he realizado un analisis bivariado de las variables categóricas y las numéricas con la variable target (is_suscribed).
cabe recalcar que para entender bien la variable objetivo 'is_suscribed' el 0 corresponde a 'no suscrito' y 1 'suscrito'. Muchas de las graficas son practicamente imposibles de entender como por ejemplo la del euribor ya que hay demasiados datos.

In [ ]:
df.correlation = df[numerical_vars].corr()
plt.figure(figsize=(12, 8))
sns.heatmap(df.correlation, annot=True, cmap='coolwarm', fmt=".2f")
plt.title("Correlación de variables numéricas")
plt.show()

he intentado hacer la matriz de correlacion con todas las variables (numericas y categoricas), pero con estas ultimas da error. Por lo tanto he especificado que la matriz solo contara con las variables numericas.
En este fragmento de codigo me he apoyado de la IA para utilizar el seaborn, es decir, para que la matriz de correlacion sea visualmente mas atractiva y mas facil de entender